### ISSUE TITLE
Rivedere sistema di import

### ISSUE THREAD

**Issue by ncvescera** [Typing-Monkeys/complex-network-link-prediction#33]
Probabilmente c'è un problema con gli import all'interno della libreria:
- [x] la cartella `utils` dovrebbe trovarsi all'interno di `social_network_link_prediction`
- la cartella `utils` andrebbe rinominata in `__utils` o qualcosa di simile per sottolineare l'utilizzo solo all'interno della libreria
- andrebbero utilizzati solo import relativi

**Comment by CristianCosci** [comment]
Hai un esempio per l'errore in questione?

Per quanto riguarda la cartella utils non sono sicuro sia necessario esplicitare l'utilizzo solo interno alla libreria. Magari a volte può essere utile (sia per debugging che per definire funzioni custom al di fuori della libreria) avere accesso a tali funzioni. Andrebbe valutato

**Comment by ncvescera** [comment]
Penso che il problema sia che, non essendo dentro la cartella `social_network_link_prediction`, venga considerata un modulo a parte e quindi per importarla basterebbe fare 

```python
from utils import ...
```

invece di 

```python
from social_network_link_prediction import utils
```

**Comment by CristianCosci** [comment]
okay, perfetto.
Questo andrebbe corretto e messo dentro

**Comment by ncvescera** [comment]
Risolto in commit 2c2a7ba
