### ISSUE TITLE
Testing Scikit-network problem

### ISSUE THREAD

**Issue by ncvescera** [Typing-Monkeys/complex-network-link-prediction#37]
C'è un problema con la libreria che implementa molti metodi, scikit-network: hanno rimosso la maggior parte delle implementazioni dei metodi di similarità (similarity methods/local similarity) 🙃.

Una possibile soluzione sarebbe quella di forzare come requirement (per i tests) la versione `v0.28.3`.

**Comment by CristianCosci** [comment]
Risolto in 5e80cbf
